from colas_prioridad_no_acotada import PriorityQueue
pq = PriorityQueue()
pq.enqueue(4,"Maestre")
pq.enqueue(2,"Niños")
pq.enqueue(4,"Mecánico")
pq.to_string()
pq.enqueue(3,"Hombres")
pq.enqueue(4,"Vigía")
pq.enqueue(5,"Capitán")
pq.enqueue(4,"Timonel")
pq.enqueue(3,"Mujeres")
pq.enqueue(2,"3ra edad")
pq.enqueue(1,"Niñas")
pq.to_string()
print("\nEliminado elementos: \n")
pq.denqueue()
pq.to_string()
pq.denqueue()
pq.to_string()
pq.denqueue()
pq.denqueue()
pq.denqueue()
pq.denqueue()
pq.denqueue()
pq.denqueue()
pq.denqueue()
pq.denqueue()
pq.denqueue()
print("")
print(f"La cola tiene {pq.length()} elemento(s)")
print(f"¿La lista está vacía?: {pq.is_empty()}")
