from listas import Linkedlist
l=Linkedlist()
print(f"L está vacía?: {l.is_empty()}")

l.append(10)
l.append(5)
l.append(6)
l.append(20)
print(f"L está vacía?: {l.is_empty()}")
l.transversal()
l.remove(10)
l.transversal()
l.preppend(3)
l.transversal()
l.tail()
#print(x.data)
print(l.get())
print(l.get(2))
print(l.get(10))
