from lista_circular_simple import CircularList

l = CircularList()
print(f"\n¿La lista está vacía?: {l.is_empty()}")
l.remove(22)
l.insert(30)
l.transversal()
l.remove(30)
l.transversal()
l.insert(20)
l.transversal()
l.insert(31)
l.transversal()
l.insert(40)
l.transversal()
l.insert(30.5)
l.transversal()
l.remove(30.5)
l.transversal()
l.insert(22)
l.insert(30.1)
l.insert(30.1)
l.insert(50)
l.insert(30.1)
l.insert(0.5)
l.transversal()
l.insert(55)
l.insert(35)
l.insert(60)
l.insert(66)
l.transversal()
print(f"¿La lista está vacía?: {l.is_empty()}")
l.search(66)
l.search(0)
l.remove(22)
l.transversal()
l.remove(0.5)
l.transversal()
l.remove(66)
l.transversal()
l.remove(60)
l.transversal()
l.remove(0.5)
l.remove(66)
l.remove(40)
l.remove(31)
l.remove(20)
l.remove(55)
l.remove(50)
l.remove(35)
l.transversal()
l.remove(30.1)
l.transversal()
l.remove(30)
l.transversal()
print(f"¿La lista está vacía?: {l.is_empty()}")
